# Generated by Django 4.2.4 on 2023-09-06 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jacob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JacobUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.PositiveBigIntegerField(choices=[(1, 'male'), (2, 'femail'), (3, 'unknown')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
