# Generated by Django 4.2.4 on 2023-09-09 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jacob', '0002_jacobuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jacobuser',
            name='gender',
            field=models.PositiveBigIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'unknown')]),
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('gender', models.PositiveIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'unknown')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200)),
                ('field2', models.IntegerField(default=0)),
                ('field3', models.TextField(max_length=500)),
                ('field4', models.CharField(max_length=200)),
                ('field5', models.IntegerField(default=0)),
                ('field6', models.TextField(max_length=500)),
                ('field7', models.CharField(max_length=200)),
                ('field8', models.IntegerField(default=0)),
                ('field9', models.TextField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacob.question')),
            ],
        ),
    ]
